---
- name: 'Enable and unmask sshd.socket'
  systemd:
    name: ssh.socket
    state: started
    enabled: yes
    masked: no

- name: 'Enable and unmask sshd.service'
  systemd:
    name: ssh.service
    state: started
    enabled: yes
    masked: no

- name: 'mkdir ssh.socket.d'
  file:
    path: /etc/systemd/system/ssh.socket.d
    state: directory
    owner: root
    group: root
    mode: '0755'
    follow: no

- name: 'Create ssh.socket.d/listen.conf'
  template:
    src: templates/listen_conf.j2
    dest: /etc/systemd/system/ssh.socket.d/listen.conf
    owner: root
    group: root
    mode: '0644'
    force: yes
    backup: yes
  notify: 'Restart ssh.socket'

- name: Update sshd_config
  template:
    src: templates/sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0644'
    force: yes
    backup: yes
    validate: "sshd -t -f %s"
  notify: 'Restart ssh.socket'

- name: Read moduli file
  community.general.read_csv:
    path: "{{ sshd_moduli_file }}"
    dialect: unix
    delimiter: ' '
    fieldnames:
      - timestamp
      - type
      - tests
      - trials
      - size
      - generator
      - modulus
  register: moduli

- name: Get min moduli size
  set_fact:
    moduli_min: "{{ moduli.list | map(attribute='size') | sort | first }}"
    cacheable: no

- name: Deactivate short moduli
  shell: > 
    awk '$5 >= {{ sshd_moduli_min }}' {{ sshd_moduli_file }} 
    > {{ sshd_moduli_file }}.tmp 
    && mv {{ sshd_moduli_file }}.tmp {{ sshd_moduli_file }}
  when: moduli_min | int < sshd_moduli_min
  notify: 'Restart ssh.socket'
...
