---
- name: 'Restart ssh.service'
  ansible.builtin.systemd:
    name: ssh.service
    state: restarted
    daemon_reload: true

- name: 'Restart ssh.socket'
  ansible.builtin.systemd:
    name: ssh.socket
    state: restarted
    daemon_reload: true
...
